version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: cmc_postgres
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: cmc_truyen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis cho BullMQ
  redis:
    image: redis:7-alpine
    container_name: cmc_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  pgdata: